name: Pre-receive Secret Scan
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history scan

      - name: Scan commits
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          scan-type: "commit-range"  # Checks ALL commits in push
          fail-on-error: true
          exit-code: 1  # Hard fail

      - name: Force-push rejection
        if: failure()
        run: |
          echo "::error::SECRETS DETECTED! Use 'git commit --amend' to remove them."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"state": "error"}' \
            "${{ github.api_url }}/repos/${{ github.repository }}/statuses/${{ github.sha }}"