name: Secret Scan
on: [pull_request, push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml  # Custom patterns
          fail-on-error: true          # Block if secrets found